---
title: "regressions"
author: "Nathaniel Imel"
date: "2024-05-04"
output: html_document
---


```{r imports}
library(tidyverse)
library(lme4)
library(modelr)
library(viridis)
library(ggrepel)
library(latex2exp)
library(ggridges)
library(car)
library(lmerTest)
library(lmtest)
library(broom.mixed)
library(jtools)
```

```{r load}

dirname <- "/Users/nathanielimel/uci/projects/citesim/src/notebooks/"
get_data_v <- function(vectorizer) {
  fp <- paste(dirname, vectorizer, "_main_data.csv", sep="")
  v_data <- read_csv(fp)
  v_data$vectorizer <- vectorizer
  return(v_data)
}

df_all <- rbind(
  get_data_v("SciBERT"),
  get_data_v("SBERT"),
  get_data_v("GPT2"),
  get_data_v("Word2Vec"),
  get_data_v("BOW")
)

# df_all <- read_csv("/Users/nathanielimel/uci/projects/citesim/src/notebooks/SBERT_SciBERT_GPT2_main_data.csv")
head(df_all)
```

```{r modelfuncs}

get_anova <- function(y, vectorizer_name) {
  
  df_vectorizer <- df_all %>% filter(
    vectorizer == vectorizer_name
  ) %>% mutate(
    # z-scale
    y_z = scale(.data[[y]]),
    density_bin_z = scale(density_bin),
    year_med_z = scale(year_med)
  )
  
  # Model 4: age, density, and random density slopes and intercepts
  label_4_both <- paste(
    # y,
    # " ~ year_med + density_bin + (1 + density_bin | field)"
    "y_z ~ year_med_z + density_bin_z + (1 + density_bin_z | field)"
  )
  fm_4_both <- as.formula(label_4_both)
  model_4_both <- lmer(
    fm_4_both, 
    data=df_vectorizer, 
    control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5))
  )
  
  # Model 3: density and random intercepts
  label_3_rho <- paste(
    # y,
    # "~ density_bin + (1 | field)"
    "y_z ~ density_bin_z + (1 | field)"
  )
  fm_3_rho <- as.formula(label_3_rho)
  model_3_rho <- lmer(
    fm_3_rho,
    data=df_vectorizer, 
    control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5))
  )
  
  # Model 2: age and random intercepts
  label_2_age <- paste(
    # y,
    # " ~ year_med + (1 | field)"
    "y_z ~ year_med_z + (1 | field)"
  )
  fm_2_age <- as.formula(label_2_age)
  model_2_age <- lmer(fm_2_age, data=df_vectorizer)
  
  
  # Model 1: intercept only (mean)
  label_1_int <- paste(
    # y,
    # " ~ 1"
    "y_z ~ 1"
  )
  fm_1_int <- as.formula(label_1_int)
  model_1_int <- lm(fm_1_int, data=df_vectorizer)
  
  results <- anova(
    model_4_both,
    model_3_rho,
    model_2_age,
    model_1_int
  )
  
  results_df <- tidy(results)
  
  results_model_4_both <- results_df %>% filter(
    term == "model_4_both",
  )
  
  results_annotated <- results_df %>% mutate(
    bic_gain = results$BIC - results_model_4_both$BIC,
    vectorizer = vectorizer_name,
    predictor = y,
    # Always check that the results are actually ordered in this way...should use a dict but oh well
    # fms = c(label_4_both, label_3_rho, label_2_age, label_1_int),
    # fm = c(label_1_int, label_2_age, label_3_rho, label_4_both),
  )
  print(summary(model_4_both))
  print("------------------------------")
  # print(results)
  
  return(results_annotated)
}
```


```{r filter}


# test the function
# get_anova("log_cpy_var", "SBERT")
# get_anova("cpy_med", "SBERT")
# get_anova("log_cpy_var", "SciBERT")
# get_anova("cpy_med", "SciBERT")
# get_anova("log_cpy_var", "GPT2")
# get_anova("log_cpy_var", "Word2Vec")
get_anova("log_cpy_var", "BOW")
```

```{r callbind}

df_plot <- rbind(
  get_anova("log_cpy_var", "SciBERT"),
  get_anova("log_cpy_var", "SBERT"),
  get_anova("cpy_med", "SciBERT"),
  get_anova("cpy_med", "SBERT")
) %>% filter(
  term != "model_4_both",
  term != "model_1_int",
)

(
  ggplot(
    df_plot,
    aes(
      x=bic_gain,
      y=term,
      # fill=vectorizer,
    )
  )
  + geom_bar( stat = "identity", position = "dodge")
  # + xlim(-4000, -1000)
  + theme_classic()
  # + scale_y_discrete(position = "right")
  # + scale_fill_manual( values = c("lightblue", "darkblue"))
  # + scale_fill_brewer()
  # + facet_grid("vectorizer ~ predictor")
)

```



```{r multiplot}

# it's hard to visualize via faceting because it makes significant differences in BIC look insignificant. So let's just try printing 4 separate plots with diff scales?

plot_bic <- function(df_plot) {
  
  df_plot <- df_plot %>% filter(
    # term != "model_4_both",
    term != "model_1_int",
  )
  
  plot <- (
    ggplot(
      df_plot,
      aes(
        x=bic_gain,
        y=term,
      )
    )
    + geom_bar( stat = "identity", position = "dodge")
    + theme_classic()
  )
  
  return(plot)
}

for (predictor in c("cpy_med", "log_cpy_var")){
  for (vectorizer in c("SciBERT", "SBERT")){
    print(plot_bic(
      get_anova(predictor, vectorizer)
    ))
  }
}
```


```{r summarize}

get_summary <- function(y, vectorizer_name) {
  
  df_vectorizer <- df_all %>% filter(
    vectorizer == vectorizer_name
  ) %>% mutate(
    # z-scale
    y_z = scale(.data[[y]]),
    density_bin_z = scale(density_bin),
    year_med_z = scale(year_med)
  )
  
  # Model 4: age, density, and random density slopes and intercepts
  label_4_both <- paste(
    # y,
    # " ~ year_med + density_bin + (1 + density_bin | field)"
    "y_z ~ year_med_z + density_bin_z + (1 + density_bin_z | field)"
  )
  fm_4_both <- as.formula(label_4_both)
  model_4_both <- lmer(
    fm_4_both, 
    data=df_vectorizer, 
    control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5))
  )
  print(summary(model_4_both))
  
  return(model_4_both)
  
}

tidy(get_summary("log_cpy_var", "SciBERT"))

```



```{r refs}

getrefs <- function(y, vectorizer_name, print_summary=TRUE) {
  
  df_vectorizer <- df_all %>% filter(
    vectorizer == vectorizer_name
  ) %>% mutate(
    # z-scale
    y_z = scale(.data[[y]]),
    density_bin_z = scale(density_bin),
    year_med_z = scale(year_med),
    ref_med_z = scale(ref_med),
  ) %>% filter(
    y_z < 3,
    y_z > -3,
    density_bin_z < 3,
    density_bin_z > -3,
    ref_med_z < 3,
    ref_med_z > -3
  )
  
  # Model 5: 
  label_5 <- paste(
    # "y_z ~ year_med_z + density_bin_z + (1 | field)"
    "y_z ~ ref_med_z + year_med_z + density_bin_z + (1 | field)"
    # "y_z ~ ref_med_z + year_med_z + density_bin_z + (1 + density_bin_z + ref_med_z | field)"
    # "y_z ~ ref_med_z + year_med_z + density_bin_z + (1 + density_bin_z | field)"
  )
  fm_5 <- as.formula(label_5)
  model_5 <- lmer(
    fm_5, 
    data=df_vectorizer, 
    control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5))
  )
  
  if (print_summary) {
    print(summary(model_5))    
  }
  
  model_ref_rho <- lmer(
    ref_med_z ~ density_bin_z + (1 + density_bin_z | field), 
    data=df_vectorizer,
    control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5))
  )
  
  print(summary(model_ref_rho))

  return(model_5)
  
}

# summary(getrefs("log_cpy_var", "GPT2", FALSE))
getrefs("log_cpy_var", "SciBERT", FALSE)

```


```{r forestplots}

for (y in c("cpy_med", "log_cpy_var")) {
  print(
    plot_summs(
      getrefs(y, "SciBERT",),
      getrefs(y, "SBERT"),
      getrefs(y, "GPT2"),
      getrefs(y, "Word2Vec"),
      getrefs(y, "BOW"),
      model.names = c("SciBERT", "SBERT", "GPT2", "Word2Vec", "BOW"),
      # model.names = c("SciBERT", "SBERT", "GPT2"),
      colors = "Rainbow",
      robust=TRUE, 
      inner_ci_level = .9
      # plot.distributions = TRUE
    )
      # + scale_color_viridis(discrete=TRUE)
    # + scale_color_manual( values = c("blue", "red"))
    + theme(
      axis.text.x = element_text(size=20)
    )  
  )  
  
}

```

```{r refsanalysis}

# Looks like number of references is a better predictor of the typical citation rates than density. 
# However, we have very good reason to believe that density causes number of references, not the other way around!


# Create a new df grouped by vectorizer and field (should have done this above, refactor)

df_grouped <- df_all %>%
  group_by(field, vectorizer) %>%
  mutate_at(vars(cpy_med, density_bin, year_med, ref_med),
            list(z = ~scale(.))) %>%
  filter(cpy_med_z < 3,
         cpy_med_z > -3,
         density_bin_z < 3,
         density_bin_z > -3,
         ref_med_z < 3,
         ref_med_z > -3)

# head(df_grouped)

(
  ggplot(
    df_grouped,
    aes(
      x=density_bin_z,
      y=ref_med_z,
      # color=field,
    )
  )
  + geom_smooth(
    method="lm",
    linewidth=5,
  )
  + geom_smooth(
    aes(
      color=field,      
    ),
    # method="lm",
    linewidth=1,
  )
  # + facet_grid("vectorizer ~ .")
  + facet_wrap("vectorizer")
)

getrefs("cpy_med", "SciBERT", FALSE)
getrefs("cpy_med", "SBERT", FALSE)
getrefs("cpy_med", "GPT2", FALSE)
getrefs("cpy_med", "Word2Vec", FALSE)
getrefs("cpy_med", "BOW", FALSE)

```

