---
title: "joy-density"
author: "Nathaniel Imel"
date: "2024-03-07"
output: html_document
---


```{r setup}
library(tidyverse)
library(lme4)
library(modelr)
library(viridis)
library(ggrepel)
library(latex2exp)
library(ggridges)
```


```{r load data}
# df = read_csv("/Users/nathanielimel/uci/projects/citesim/outputs/librarian=S2/vectorizer=Word2Vec/center=Imeletal2022/all_data.csv")
df = read_csv("/Users/nathanielimel/uci/projects/citesim/outputs/librarian=S2/vectorizer=SciBERT/center=hafenLowredshiftLymanLimit2017/all_data.csv")
df
```


```{r transform}

df_filtered <- df %>% filter(
  citations_per_year >= 1,
  citations_per_year <= 100,
)

```

```{r transform_func}


metric_to_df_zf <- function(df_in, metric) {
  # Filter to 2 stds, for both vars
  metric_z <- paste(metric, "_z", sep="")

  df_z <- df_in %>% mutate(
    df_in,
    metric_z = scale(.data[[metric]]),
    cpy_z = scale(citations_per_year),
  )
  
  # Add log transform
  df_z <- df_z %>% mutate(
    df_z,
    logcpy = log10( citations_per_year ),
    logcpy_z = log10( cpy_z ),
  )

  # Get the center to label
  # N.B.: if the python script raised a warning, this dataframe will be empty and no point will be plotted.
  df_center <- df_z %>% filter(
    is_center == TRUE
  )
  # print("DF CENTER:")
  # print(df_center)  
  
  # Filter to mean cpys
  # TODO: sometimes the center will have more than mean!
  # Maybe do +1 std?
  df_z <- df_z %>%
    filter(
      cpy_z <= 2
    )

  df_zf <- df_z %>% filter(
    (
      metric_z >= -2
      & 
      metric_z <= 2
    ),
  )

  return(df_zf)
}

df_zf <- metric_to_df_zf(df_filtered, "density")
df_zf
```
```{r bins}

df_zf$density_bin <- cut(
  df_zf$density, 
  breaks = seq(
    min(df_zf$density), 
    max(df_zf$density), 
    length.out = 11
  )
)

```

```{r lines}
(
  ggplot(
    df_zf,
    aes(
      x = citations_per_year,
      color = density_bin,
    )
  )
  + geom_density()
  # + scale_x_log10()
  + scale_color_viridis(discrete = TRUE)
)

```


```{r filledlines}
(
  ggplot(
    df_zf,
    aes(
      x = citations_per_year,
      color = density_bin,
      fill = density_bin,
    )
  )
  + geom_density(aes(y = after_stat(count)), alpha = 0.2)
  # + scale_x_log10()
  + scale_color_viridis(discrete = TRUE)
  + scale_fill_viridis(discrete = TRUE)
  
  # + xlim(8,10)
)

```

```{r hist}
(
  ggplot(
    df_zf,
    aes(
      x = citations_per_year,
      color = density_bin,
      fill = density_bin,
    )
  )
  + geom_histogram(position="dodge")
  # + scale_x_log10()
  + scale_color_viridis(discrete = TRUE)
  + scale_fill_viridis(discrete = TRUE)

  
)

```


```{r ridges}

(
  ggplot(
    df_zf,
    aes(
      x = citations_per_year,
      y = density_bin,
      color = density_bin,
      fill = density_bin,
      alpha = 0.2,
    )
  )
  + geom_density_ridges()
  + scale_x_log10()
  # + xlim(8,10)
  + scale_color_viridis(discrete = TRUE)
  + scale_fill_viridis(discrete = TRUE)

)

```

```{r blob}

(
    ggplot(
      df_zf,
      mapping=aes(
        # x=density_z, 
        x=density, # NOTE that we filter by z-scale, but can still plot the orig values.
        y=citations_per_year
      )
    )
    + geom_density_2d_filled(
      contour_var = "ndensity",
      # alpha=0.2,
    )
    + scale_fill_viridis(option = "viridis", discrete = TRUE)
    + xlab("Density")
    # + ylab("Citations per year")
    + ylab("Citations per year")

    # Local linear regression
    + geom_smooth(color="orange", size=2, method="loess", span=.3)

    # Running binned median
    + stat_summary_bin(fun = "median", geom = "smooth", bins = 10)

    + geom_point(
      alpha=0.05,
      color="white",
      size=1,
    )
    
    + ylim(0, NA)
    + theme(
      # axis_title_y=element_blank(),
      axis.title=element_text(size=18),
    )
  )

```
