---
title: "main_xy_plot"
author: "Nathaniel Imel"
date: "2024-04-26"
output: html_document
---
  
  
```{r setup}
library(tidyverse)
library(lme4)
library(modelr)
library(viridis)
library(ggrepel)
library(latex2exp)
```



```{r load}
df <- read_csv("dmb_vs_log_cpy_var.csv")
head(df)
```

```{r statties}

# normally we'd z-scale etc and predict from that
# but i just want an annotation for the figure

model <- lm(log_cpy_var ~ density_med_bin, data=df)
summary(model)
```


```{r plot}

(
        ggplot(
            df,
            aes(
                x=density_med_bin,
                # y=log_cpy_med_bin,
                # y=log_cpy_var,
                # y=cpy_var,
                y=cpy_med_bin,
                # color=field,
                # shape="field",
            )
        )
        # + facet_wrap("field")
        + geom_point(
            aes(
                # shape=field,
                # color=field,
            ),
            # color="black",
            alpha=0.3,
        )
        + stat_summary_bin(fun = "median", geom = "smooth", bins = 4., color="black", size=3,)
        # + stat_summary_bin(fun = "median", geom = "smooth", bins = 4., mapping = aes(color=field) )
        + geom_smooth(
            aes(
                color=field,
            ),
            method="lm",
            # color="black",
            level=0,
        )
        + scale_y_log10()
        + ylab("Variance in citations per year")
        + xlab("Density of existing research")
        + theme_classic()
        # + ylim(0,2)
    )

```


```{r save}

ggsave(
  filename = "main_xy.png",
)

```