---
title: "references"
author: "Nathaniel Imel"
date: "2024-04-23"
output: html_document
---
  
  
```{r setup}
library(tidyverse)
library(lme4)
library(modelr)
library(viridis)
library(ggrepel)
library(latex2exp)
library(ggridges)
library(car)
```

```{r load}
df_all <- read_csv("../../analysis_data/all_data.csv")
head(df_all)
```

```{r plot}

df <- df_all %>% mutate(
  references_z = scale(references),
  density_z = scale(density),
) %>% filter(
  references_z < 2,
  density_z < 2,
)

(
    ggplot(
        df,
        # df,
        aes(
            x=density,
            y=references,
            color=fields_of_study_0,
        )
    )
    # + scale_y_log10()
    + geom_point(alpha=0.01)
    + geom_smooth()
    # + facet_wrap("fields_of_study_0")
    + xlab("Prior density of neighborhood")
    + ylab("Number of references")
    + theme_minimal()
    # TODO: annotate each line with R^2, p-values
    # TODO: normalize each by the average number of references per field
)

```


```{r save}

ggsave(
  filename = "references_faceted.png",
  
)

```

```{r load2}

df_var <- read_csv("/Users/nathanielimel/uci/projects/citesim/src/notebooks/all_cpy_variance_data.csv")
head(df_var)
```


```{r plot2}

# df_var <- df_var %>% mutate(
#   density_bin_z = scale(density_bin),
# ) %>% filter(
#   density_bin_z < 2
# )

(
        ggplot(
            df_var, 
            aes(
                x=year_med,
                # y=log_cpy_var,
                y=cpy_med,
                # y=`log_cpy median`,
                color=field,
                # shape=field,
            )
        )
        # + facet_wrap("field")
        + geom_point(
            aes(
                # size=freq,
                alpha=freq,
            )
        )
        # + scale_y_log10()
        + geom_smooth(method="lm")
        # + ylab("Variance in citations per year")
        # + xlab("Prior density of neighborhood")
        + theme_classic()
)

```


```{r stats}

# install.packages("lmerTest")
library(lmerTest)

# First model



# model0 <- lmer(citations_per_year ~ (density | fields_of_study_0) , data=df_all)
# model0 <- lmer(log_cpy_variance ~ density_bin + (density_bin | field ), data=df_var)
# model0 <- lm(log_cpy_variance ~ density_bin, data=df_var)
model_big <- lmer(log_cpy_var ~ year_med + (1 + year_med | field) + density_bin + (1 + density_bin | field), data=df_var)

# Okay, fine. Well I can stil freeze to a specific year and then compute these results. 

summary(model_big)
```



```{r models}

# model_interaction <- lmer(log_cpy_var ~ year_med*density_bin + (1 + density_bin + year_med | field), data=df_var, control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

model_4_both <- lmer(log_cpy_var ~ year_med + density_bin + (1 + density_bin | field), data=df_var, control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

model_3_rho <- lmer(log_cpy_var ~ density_bin + (1 | field), data=df_var, control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

model_2_age <- lmer(log_cpy_var ~ year_med + (1 | field), data=df_var)

# model_ints1 <- lmer(log_cpy_var ~ 1 + (1 + year_med | field), data=df_var, control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

# model_ints0 <- lmer(log_cpy_var ~ (1 + year_med | field), data=df_var, control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

model_1_int <- lm(log_cpy_var ~ 1, data=df_var)

summary(model_4_both)
```


```{r anova}

library(lmtest)


anova_results <- anova(
  model_4_both,
  model_3_rho,
  model_2_age,
  model_1_int
)

# The fact that loglik is higher under lrtest for just density than the both model makes me think we should just compare three models, rho, age and baseline intercept
anova_results
```

```{r visanova}

anova_df <- tidy(anova_results)

# model_both is so close to model_rho so we drop it
anova_df_vis <- anova_df %>% filter(
  term != "model_4_both",
)

anova_df_vis$BIC_gain <- anova_df_vis$BIC - anova_df[4,4]$BIC

(
  ggplot(
    anova_df_vis,
    aes(
      x=BIC_gain,
      y=term,
    )
  )
  + geom_bar( stat = "identity")
  # + xlim(-4000, -1000)
)

```







```{r hist}
(
  ggplot(df_var, aes(x=year_med))
  # + geom_histogram()
  + geom_density()
)

(
  ggplot(df_var, aes(x=density_bin))
  # + geom_histogram()
  + geom_density()
)

```

```{r freeze}

df_2010 <- df_var %>% filter(
  year_med == 2010,
)

model0 <- lmer(cpy_med ~ density_bin + (1 + density_bin | field), data=df_2010)
print(summary(model0))

model1 <- lmer(cpy_med ~ (1 | field), data=df_2010)
print(summary(model1))
```


```{r compare}

library(lmtest)

model_big <- lmer(log_cpy_var ~ year_med + (1 + year_med | field) + density_bin + (1 + density_bin | field), data=df_var)

model_small <- lmer(log_cpy_var ~ density_bin + (1 + density_bin | field), data=df_var)

```

```{r likratio}


lrtest(model_big, model_small)

# Reject the null - ifmodel 2 is a better fit

```

```{r aic}

print(summary(model_big))

print(summary(model_small))
```
