name: citesim
channels:
  - conda-forge
dependencies:
  - matplotlib=3.5
  - pandas
  - tqdm
  - black
  - plotnine
  - pip
  - pip:
    - hydra-core  
    - cmdstanpy
  - pygmo
  - numpy
  - pytorch
# and sciterra, installed via git for now
