##############################################################################
# MAIN CONFIG FILE
##############################################################################

defaults:
  - experiment: dev
  - override hydra/job_logging: custom  
  - _self_ # stuff below can override stuff above  

seed: 42

##############################################################################
# Paths of files used for consuming and producing data
##############################################################################
filepaths: 

  ############################################################################
  # Data to read in
  ############################################################################

  atlas_center_bibtex: data/bib/${experiment.atlas.center}.bib

  ############################################################################
  # Outputs
  ############################################################################  

  ############################################################################
  # Hydra automatic folder naming
  ############################################################################


  # Let vectorizer model be possibly saved in intermediate level of folder hierarchy so we can load the same one for diff parameter sweeps.
  vectorizer_subdir: librarian=${experiment.librarian.name}/vectorizer=${experiment.vectorizer.name} # N.B.: vectorizers of the same name will not be distinguished even if they were given different kwargs.

  experiment_subdir: ${filepaths.vectorizer_subdir}/center=${experiment.atlas.center}

  # where the current working directory will be when hydra is running
  leaf_subdir: ${filepaths.experiment_subdir}

  # hydra run root directory
  hydra_run_root: outputs

  # hydra multirun root directory
  hydra_sweep_root: multirun

##############################################################################
# Hydra run and sweep configs
##############################################################################
hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - experiment.librarian.name
          - experiment.vectorizer.name
          - experiment.atlas.center
          - seed

  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}
