hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers:
      - console
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - experiment.vectorizer.name=SciBERT
    - experiment.atlas.center=Imeletal2022
    - experiment.cartography.required_pub_conditions.fields_of_study=[Linguistics]
    - experiment.plot.update_ind=null
    - experiment.plot.con_d=0.27
  job:
    name: analyze
    chdir: true
    override_dirname: experiment.cartography.required_pub_conditions.fields_of_study=[Linguistics],experiment.plot.con_d=0.27,experiment.plot.update_ind=null
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
        - experiment.librarian.name
        - experiment.vectorizer.name
        - experiment.atlas.center
        - seed
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/nathanielimel/uci/projects/citesim
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/nathanielimel/uci/projects/citesim/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      experiment: dev
      experiment/plot: dev
      experiment/cartography: dev
      experiment/cartography/required_pub_conditions: dev
      experiment/cartography/required_pub_conditions/fields_of_study: physics
      experiment/cartography/required_pub_conditions/attributes: abs_pub_fields
      experiment/atlas: dev
      experiment/vectorizer: scibert
      experiment/librarian: semanticscholar
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: custom
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
experiment:
  librarian:
    name: S2
    kwargs:
      api_key_fn: null
  vectorizer:
    name: SciBERT
    kwargs:
      device: mps
  atlas:
    center: Imeletal2022
  cartography:
    required_pub_conditions:
      attributes:
      - abstract
      - publication_date
      - fields_of_study
      fields_of_study:
      - Linguistics
    target_size: 100
    max_failed_expansions: 2
    n_pubs_max: 10
    batch_size: 64
    call_size: null
  plot:
    max_density: null
    log_cpy: null
    con_d: 0.27
    update_ind: null
seed: 42
filepaths:
  atlas_center_bibtex: data/bib/${experiment.atlas.center}.bib
  vectorizer_subdir: librarian=${experiment.librarian.name}/vectorizer=${experiment.vectorizer.name}
  experiment_subdir: ${filepaths.vectorizer_subdir}/center=${experiment.atlas.center}
  leaf_subdir: ${filepaths.experiment_subdir}
  hydra_run_root: outputs
  hydra_sweep_root: multirun
